package com.dhaaga.app.ui.seller

import android.graphics.Bitmap
import android.net.Uri
import androidx.compose.animation.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.RotateLeft
import androidx.compose.material.icons.automirrored.filled.RotateRight
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import coil.compose.AsyncImage
import com.dhaaga.app.data.repository.GeminiAIService
import com.dhaaga.app.data.repository.ImageGenerationMode
import com.dhaaga.app.data.repository.MagicHourService
import com.dhaaga.app.data.repository.StudioAngle
import com.dhaaga.app.data.repository.StudioLighting
import com.dhaaga.app.data.repository.StudioPreset
import com.dhaaga.app.data.repository.StudioSurface
import com.dhaaga.app.ui.theme.*
import com.dhaaga.app.utils.AppLanguageManager
import kotlinx.coroutines.launch
import java.io.File
import java.io.FileOutputStream

@Composable
fun AIStudioDialog(
    originalUri: Uri,
    originalBitmap: Bitmap?,
    onDismiss: () -> Unit,
    onEnhancedImageReady: (Uri, Bitmap) -> Unit
) {
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()
    val currentLang = remember { AppLanguageManager.getCurrentLanguage(context) }

    fun tr(key: String, fallback: String): String =
        AppLanguageManager.translate(key, currentLang, fallback)

    var selectedAngle by remember { mutableStateOf(StudioAngle.FRONT_VIEW) }
    var selectedSurface by remember { mutableStateOf(StudioSurface.WHITE_STUDIO) }
    var selectedLighting by remember { mutableStateOf(StudioLighting.STUDIO_SOFTBOX) }

    // Prompt Text
    var promptText by remember {
        mutableStateOf(GeminiAIService.buildStudioPrompt(selectedAngle, selectedSurface, selectedLighting))
    }

    var currentSourceBitmap by remember { mutableStateOf(originalBitmap) }
    var enhancedBitmap by remember { mutableStateOf<Bitmap?>(null) }
    var isProcessing by remember { mutableStateOf(false) }
    var showOriginal by remember { mutableStateOf(false) }
    var statusMessage by remember { mutableStateOf(tr("ready_to_transform", "Ready to transform")) }
    var isCloudGenerated by remember { mutableStateOf(false) }
    var showSettingsDialog by remember { mutableStateOf(false) }

    val generationMode = remember(showSettingsDialog) { MagicHourService.getGenerationMode(context) }
    val activeModel = remember(showSettingsDialog) { MagicHourService.getSelectedModel(context) }
    val activeKeyIndex = remember(showSettingsDialog) { MagicHourService.getActiveKeyIndex(context) + 1 }

    fun updatePromptFromPresets(
        angle: StudioAngle = selectedAngle,
        surface: StudioSurface = selectedSurface,
        lighting: StudioLighting = selectedLighting
    ) {
        selectedAngle = angle
        selectedSurface = surface
        selectedLighting = lighting
        promptText = GeminiAIService.buildStudioPrompt(angle, surface, lighting)
    }

    fun triggerEnhancement(target: Bitmap? = currentSourceBitmap) {
        val bmp = target ?: return
        if (!isProcessing) {
            coroutineScope.launch {
                isProcessing = true
                statusMessage = if (generationMode == ImageGenerationMode.API)
                    "${tr("initializing_magic_hour", "Initializing Magic Hour")} ($activeModel)..."
                else
                    tr("ondevice_segmenting", "On-Device Studio: Segmenting subject with ML Kit...")

                val result = GeminiAIService.enhanceProductImage(
                    context = context,
                    inputBitmap = bmp,
                    preset = StudioPreset.WHITE_STUDIO,
                    angle = selectedAngle,
                    surface = selectedSurface,
                    lighting = selectedLighting,
                    customInstructions = promptText,
                    onStatusUpdate = { progressText ->
                        statusMessage = progressText
                    }
                )
                result.onSuccess {
                    enhancedBitmap = it.enhancedBitmap
                    isCloudGenerated = it.isCloudAiGenerated
                    statusMessage = it.message
                }
                result.onFailure {
                    statusMessage = "${tr("enhancement_failed", "Enhancement failed")}: ${it.localizedMessage ?: tr("unknown_error", "Unknown error")}"
                }
                isProcessing = false
            }
        }
    }

    fun rotateNormalTool(degrees: Float) {
        val matrix = android.graphics.Matrix().apply { postRotate(degrees) }
        enhancedBitmap?.let { bmp ->
            enhancedBitmap = Bitmap.createBitmap(bmp, 0, 0, bmp.width, bmp.height, matrix, true)
        }
        currentSourceBitmap?.let { src ->
            currentSourceBitmap = Bitmap.createBitmap(src, 0, 0, src.width, src.height, matrix, true)
        }
    }

    // Run initial enhancement on open if originalBitmap is available
    LaunchedEffect(originalBitmap) {
        if (originalBitmap != null && enhancedBitmap == null) {
            triggerEnhancement(originalBitmap)
        }
    }

    Dialog(
        onDismissRequest = onDismiss,
        properties = DialogProperties(usePlatformDefaultWidth = false)
    ) {
        Surface(
            modifier = Modifier
                .fillMaxSize()
                .padding(10.dp),
            shape = RoundedCornerShape(24.dp),
            color = DhaagaSurface,
            tonalElevation = 8.dp
        ) {
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .verticalScroll(rememberScrollState())
                    .padding(16.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                // Header
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Box(
                            modifier = Modifier
                                .size(40.dp)
                                .clip(CircleShape)
                                .background(Brush.linearGradient(listOf(DhaagaPrimary, DhaagaPrimaryLight))),
                            contentAlignment = Alignment.Center
                        ) {
                            Icon(Icons.Default.AutoAwesome, contentDescription = null, tint = Color.White)
                        }
                        Spacer(modifier = Modifier.width(10.dp))
                        Column {
                            Text(tr("studio_title", "AI Studio Photography"), fontSize = 16.sp, fontWeight = FontWeight.Bold, color = DhaagaTextDark)
                            Text(
                                if (generationMode == ImageGenerationMode.API)
                                    "Magic Hour API • $activeModel (${tr("slot_label", "Slot")} #$activeKeyIndex)"
                                else
                                    tr("mode_on_device_sub", "On-Device Studio • ML Kit Engine"),
                                fontSize = 11.sp,
                                color = DhaagaPrimary,
                                fontWeight = FontWeight.SemiBold
                            )
                        }
                    }

                    Row(verticalAlignment = Alignment.CenterVertically) {
                        IconButton(onClick = { showSettingsDialog = true }) {
                            Icon(Icons.Default.Tune, contentDescription = tr("settings_ai_title", "AI Settings"), tint = DhaagaPrimary)
                        }
                        IconButton(onClick = onDismiss) {
                            Icon(Icons.Default.Close, contentDescription = tr("close_btn", "Close"), tint = DhaagaTextMedium)
                        }
                    }
                }

                // Main Image Preview Area with Before/After
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(260.dp)
                        .clip(RoundedCornerShape(18.dp))
                        .background(Color(0xFFF0EFEB))
                        .border(1.dp, DhaagaDivider.copy(alpha = 0.5f), RoundedCornerShape(18.dp)),
                    contentAlignment = Alignment.Center
                ) {
                    if (isProcessing) {
                        Column(
                            horizontalAlignment = Alignment.CenterHorizontally,
                            verticalArrangement = Arrangement.Center,
                            modifier = Modifier.padding(20.dp)
                        ) {
                            CircularProgressIndicator(color = DhaagaPrimary, modifier = Modifier.size(46.dp), strokeWidth = 3.5.dp)
                            Spacer(modifier = Modifier.height(14.dp))
                            Text(
                                tr("studio_loading_title", "Rendering Studio Photography..."),
                                fontSize = 14.sp,
                                fontWeight = FontWeight.Bold,
                                color = DhaagaPrimary
                            )
                            Spacer(modifier = Modifier.height(6.dp))
                            Text(
                                statusMessage,
                                fontSize = 11.5.sp,
                                color = DhaagaTextMedium,
                                textAlign = TextAlign.Center
                            )
                        }
                    } else {
                        val displayBitmap = if (showOriginal) currentSourceBitmap else (enhancedBitmap ?: currentSourceBitmap)
                        if (displayBitmap != null) {
                            Image(
                                bitmap = displayBitmap.asImageBitmap(),
                                contentDescription = tr("studio_product_cd", "Studio Product"),
                                contentScale = ContentScale.Fit,
                                modifier = Modifier.fillMaxSize()
                            )
                        } else {
                            AsyncImage(
                                model = originalUri,
                                contentDescription = tr("original_photo_cd", "Original Photo"),
                                contentScale = ContentScale.Fit,
                                modifier = Modifier.fillMaxSize()
                            )
                        }

                        // Compare Toggle Button
                        Box(
                            modifier = Modifier
                                .align(Alignment.BottomEnd)
                                .padding(10.dp)
                                .clip(RoundedCornerShape(30.dp))
                                .background(Color.Black.copy(alpha = 0.8f))
                                .clickable { showOriginal = !showOriginal }
                                .padding(horizontal = 12.dp, vertical = 6.dp)
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Icon(
                                    imageVector = if (showOriginal) Icons.Default.VisibilityOff else Icons.Default.Visibility,
                                    contentDescription = null,
                                    tint = Color.White,
                                    modifier = Modifier.size(14.dp)
                                )
                                Spacer(modifier = Modifier.width(6.dp))
                                Text(
                                    if (showOriginal) tr("raw_camera", "Raw Camera") else tr("studio_enhanced", "Studio Enhanced"),
                                    fontSize = 11.sp,
                                    color = Color.White,
                                    fontWeight = FontWeight.SemiBold
                                )
                            }
                        }

                        val badgeBgColor: Color = when {
                            showOriginal -> Color.Gray.copy(alpha = 0.85f)
                            isCloudGenerated -> DhaagaPrimary.copy(alpha = 0.95f)
                            else -> DhaagaPrimaryLight.copy(alpha = 0.95f)
                        }

                        val badgeText = when {
                            showOriginal -> tr("badge_raw", "RAW CAMERA")
                            isCloudGenerated -> "${tr("badge_ai_studio", "AI STUDIO")} • $activeModel"
                            else -> "${tr("badge_ai_studio", "AI STUDIO")} • ${tr("surface_white_studio", "PURE WHITE")}"
                        }

                        // Quality Badge
                        Box(
                            modifier = Modifier
                                .align(Alignment.TopStart)
                                .padding(10.dp)
                                .clip(RoundedCornerShape(8.dp))
                                .background(badgeBgColor)
                                .padding(horizontal = 10.dp, vertical = 4.dp)
                        ) {
                            Text(
                                text = badgeText,
                                fontSize = 9.5.sp,
                                fontWeight = FontWeight.Bold,
                                color = Color.White,
                                letterSpacing = 0.5.sp
                            )
                        }
                    }
                }

                // ----------------------------------------------------
                // PRESET PROMPTS: ANGLES, SURFACES, & LIGHTING
                // ----------------------------------------------------
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(16.dp),
                    colors = CardDefaults.cardColors(containerColor = Color(0xFFFAF9F6)),
                    border = BorderStroke(1.dp, DhaagaDivider.copy(alpha = 0.6f))
                ) {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(12.dp),
                        verticalArrangement = Arrangement.spacedBy(10.dp)
                    ) {
                        // Section Title + Reset Button
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Icon(Icons.Default.FilterFrames, contentDescription = null, tint = DhaagaPrimary, modifier = Modifier.size(16.dp))
                                Spacer(modifier = Modifier.width(6.dp))
                                Text(tr("preset_staging_title", "Preset Staging & Perspectives"), fontSize = 12.5.sp, fontWeight = FontWeight.Bold, color = DhaagaTextDark)
                            }

                            // Prominent Reset Prompt Button
                            OutlinedButton(
                                onClick = {
                                    updatePromptFromPresets(
                                        angle = StudioAngle.FRONT_VIEW,
                                        surface = StudioSurface.WHITE_STUDIO,
                                        lighting = StudioLighting.STUDIO_SOFTBOX
                                    )
                                    promptText = MagicHourService.DEFAULT_COMMERCIAL_PROMPT
                                },
                                shape = RoundedCornerShape(8.dp),
                                contentPadding = PaddingValues(horizontal = 8.dp, vertical = 2.dp),
                                modifier = Modifier.height(26.dp)
                            ) {
                                Icon(Icons.Default.RestartAlt, contentDescription = null, modifier = Modifier.size(12.dp), tint = DhaagaPrimary)
                                Spacer(modifier = Modifier.width(4.dp))
                                Text(tr("reset_prompt_btn", "Reset Prompt"), fontSize = 10.sp, fontWeight = FontWeight.Bold, color = DhaagaPrimary)
                            }
                        }

                        // 1. Camera Angle Chips
                        Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                            Text(tr("camera_angle_label", "Camera Angle:"), fontSize = 11.sp, fontWeight = FontWeight.SemiBold, color = DhaagaTextMedium)
                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .horizontalScroll(rememberScrollState()),
                                horizontalArrangement = Arrangement.spacedBy(6.dp)
                            ) {
                                StudioAngle.entries.forEach { angle ->
                                    val isSelected = selectedAngle == angle
                                    val angleLabel = when (angle) {
                                        StudioAngle.FRONT_VIEW -> tr("angle_front_view", angle.displayName)
                                        StudioAngle.TOP_ANGLE -> tr("angle_top_angle", angle.displayName)
                                        StudioAngle.RIGHT_45 -> tr("angle_right_45", angle.displayName)
                                        StudioAngle.LEFT_45 -> tr("angle_left_45", angle.displayName)
                                        StudioAngle.MACRO_DETAIL -> tr("angle_macro_detail", angle.displayName)
                                    }
                                    FilterChip(
                                        selected = isSelected,
                                        onClick = { updatePromptFromPresets(angle = angle) },
                                        label = { Text(angleLabel, fontSize = 11.sp, fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Normal) },
                                        colors = FilterChipDefaults.filterChipColors(
                                            selectedContainerColor = DhaagaPrimary,
                                            selectedLabelColor = Color.White
                                        )
                                    )
                                }
                            }
                        }

                        // 2. Table Surface Chips
                        Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                            Text(tr("surface_backdrop_label", "Surface / Backdrop:"), fontSize = 11.sp, fontWeight = FontWeight.SemiBold, color = DhaagaTextMedium)
                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .horizontalScroll(rememberScrollState()),
                                horizontalArrangement = Arrangement.spacedBy(6.dp)
                            ) {
                                StudioSurface.entries.forEach { surface ->
                                    val isSelected = selectedSurface == surface
                                    val surfaceLabel = when (surface) {
                                        StudioSurface.WHITE_STUDIO -> tr("surface_white_studio", surface.displayName)
                                        StudioSurface.MARBLE_TABLE -> tr("surface_marble_table", surface.displayName)
                                        StudioSurface.WOODEN_TABLE -> tr("surface_wooden_table", surface.displayName)
                                        StudioSurface.LINEN_FABRIC -> tr("surface_linen_fabric", surface.displayName)
                                        StudioSurface.DARK_SLATE -> tr("surface_dark_slate", surface.displayName)
                                    }
                                    FilterChip(
                                        selected = isSelected,
                                        onClick = { updatePromptFromPresets(surface = surface) },
                                        label = { Text(surfaceLabel, fontSize = 11.sp, fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Normal) },
                                        colors = FilterChipDefaults.filterChipColors(
                                            selectedContainerColor = DhaagaPrimary,
                                            selectedLabelColor = Color.White
                                        )
                                    )
                                }
                            }
                        }

                        // 3. Lighting Mood Chips
                        Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                            Text(tr("lighting_mood_label", "Lighting Mood:"), fontSize = 11.sp, fontWeight = FontWeight.SemiBold, color = DhaagaTextMedium)
                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .horizontalScroll(rememberScrollState()),
                                horizontalArrangement = Arrangement.spacedBy(6.dp)
                            ) {
                                StudioLighting.entries.forEach { lighting ->
                                    val isSelected = selectedLighting == lighting
                                    val lightingLabel = when (lighting) {
                                        StudioLighting.STUDIO_SOFTBOX -> tr("lighting_softbox", lighting.displayName)
                                        StudioLighting.WARM_SUNLIGHT -> tr("lighting_sunlight", lighting.displayName)
                                        StudioLighting.DRAMATIC_RIM -> tr("lighting_rim", lighting.displayName)
                                        StudioLighting.DIFFUSED_DAYLIGHT -> tr("lighting_daylight", lighting.displayName)
                                    }
                                    FilterChip(
                                        selected = isSelected,
                                        onClick = { updatePromptFromPresets(lighting = lighting) },
                                        label = { Text(lightingLabel, fontSize = 11.sp, fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Normal) },
                                        colors = FilterChipDefaults.filterChipColors(
                                            selectedContainerColor = DhaagaPrimary,
                                            selectedLabelColor = Color.White
                                        )
                                    )
                                }
                            }
                        }

                        // 4. Editable Prompt TextField
                        Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Text(tr("active_prompt_label", "Active AI Edit Prompt:"), fontSize = 11.sp, fontWeight = FontWeight.SemiBold, color = DhaagaTextMedium)
                                Text(tr("live_edit_badge", "Live Edit"), fontSize = 10.sp, color = DhaagaPrimary, fontWeight = FontWeight.Medium)
                            }
                            OutlinedTextField(
                                value = promptText,
                                onValueChange = { promptText = it },
                                placeholder = { Text(tr("prompt_placeholder", "E.g., front angle, marble table, studio lighting..."), fontSize = 11.sp) },
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(78.dp),
                                shape = RoundedCornerShape(10.dp),
                                textStyle = androidx.compose.ui.text.TextStyle(fontSize = 11.sp, lineHeight = 15.sp),
                                colors = OutlinedTextFieldDefaults.colors(
                                    focusedBorderColor = DhaagaPrimary,
                                    cursorColor = DhaagaPrimary
                                )
                            )
                        }
                    }
                }

                // Row 1: Rotation Tools & Generate/Re-enhance
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    OutlinedButton(
                        onClick = { rotateNormalTool(-90f) },
                        modifier = Modifier
                            .weight(1f)
                            .height(44.dp),
                        shape = RoundedCornerShape(12.dp),
                        contentPadding = PaddingValues(horizontal = 4.dp)
                    ) {
                        Icon(Icons.AutoMirrored.Filled.RotateLeft, contentDescription = null, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(4.dp))
                        Text(tr("rotate_left_btn", "Rotate Left"), fontSize = 11.sp, fontWeight = FontWeight.SemiBold, maxLines = 1, softWrap = false, color = DhaagaTextDark)
                    }

                    OutlinedButton(
                        onClick = { rotateNormalTool(90f) },
                        modifier = Modifier
                            .weight(1f)
                            .height(44.dp),
                        shape = RoundedCornerShape(12.dp),
                        contentPadding = PaddingValues(horizontal = 4.dp)
                    ) {
                        Icon(Icons.AutoMirrored.Filled.RotateRight, contentDescription = null, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(4.dp))
                        Text(tr("rotate_right_btn", "Rotate Right"), fontSize = 11.sp, fontWeight = FontWeight.SemiBold, maxLines = 1, softWrap = false, color = DhaagaTextDark)
                    }

                    Button(
                        onClick = { triggerEnhancement(currentSourceBitmap) },
                        enabled = !isProcessing,
                        modifier = Modifier
                            .weight(1.3f)
                            .height(44.dp),
                        shape = RoundedCornerShape(12.dp),
                        colors = ButtonDefaults.buttonColors(containerColor = DhaagaPrimary),
                        contentPadding = PaddingValues(horizontal = 4.dp)
                    ) {
                        Icon(Icons.Default.AutoFixHigh, contentDescription = null, modifier = Modifier.size(15.dp), tint = Color.White)
                        Spacer(modifier = Modifier.width(4.dp))
                        Text(tr("apply_ai_edit_btn", "Apply AI Edit"), fontSize = 11.sp, fontWeight = FontWeight.Bold, maxLines = 1, softWrap = false, color = Color.White)
                    }
                }

                // Row 2: Cancel & Use Studio Photo
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    OutlinedButton(
                        onClick = onDismiss,
                        modifier = Modifier
                            .weight(1f)
                            .height(48.dp),
                        shape = RoundedCornerShape(14.dp)
                    ) {
                        Text(tr("cancel_btn", "Cancel"), fontSize = 13.sp, fontWeight = FontWeight.Medium, maxLines = 1, softWrap = false, color = DhaagaTextDark)
                    }

                    Button(
                        onClick = {
                            val finalBitmap = enhancedBitmap ?: currentSourceBitmap
                            if (finalBitmap != null) {
                                try {
                                    val cacheFile = File(context.cacheDir, "studio_enhanced_${System.currentTimeMillis()}.jpg")
                                    FileOutputStream(cacheFile).use { fos ->
                                        finalBitmap.compress(Bitmap.CompressFormat.JPEG, 92, fos)
                                    }
                                    val fileUri = Uri.fromFile(cacheFile)
                                    onEnhancedImageReady(fileUri, finalBitmap)
                                } catch (e: Exception) {
                                    onEnhancedImageReady(originalUri, finalBitmap)
                                }
                            }
                        },
                        enabled = !isProcessing && (enhancedBitmap != null || currentSourceBitmap != null),
                        modifier = Modifier
                            .weight(1.8f)
                            .height(48.dp),
                        shape = RoundedCornerShape(14.dp),
                        colors = ButtonDefaults.buttonColors(containerColor = DhaagaPrimary)
                    ) {
                        Icon(Icons.Default.CheckCircle, contentDescription = null, tint = Color.White, modifier = Modifier.size(18.dp))
                        Spacer(modifier = Modifier.width(6.dp))
                        Text(tr("use_studio_photo_btn", "Use Studio Photo"), fontSize = 13.sp, fontWeight = FontWeight.Bold, maxLines = 1, softWrap = false, color = Color.White)
                    }
                }
            }
        }
    }

    if (showSettingsDialog) {
        AISettingsDialog(onDismiss = { showSettingsDialog = false })
    }

    if (isProcessing) {
        StudioLoadingDialog(
            isGenerating = isProcessing,
            generationMode = generationMode,
            activeModel = activeModel,
            activeKeySlot = activeKeyIndex,
            backendStatusMessage = statusMessage,
            onDismissRequest = { /* Keep modal during generation */ }
        )
    }
}
