package com.dhaaga.app.ui.seller

import android.graphics.Bitmap
import android.net.Uri
import androidx.compose.animation.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.RotateLeft
import androidx.compose.material.icons.automirrored.filled.RotateRight
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import coil.compose.AsyncImage
import com.dhaaga.app.data.repository.GeminiAIService
import com.dhaaga.app.data.repository.StudioLighting
import com.dhaaga.app.data.repository.StudioPreset
import com.dhaaga.app.ui.theme.*
import kotlinx.coroutines.launch
import java.io.File
import java.io.FileOutputStream

@Composable
fun AIStudioDialog(
    originalUri: Uri,
    originalBitmap: Bitmap?,
    onDismiss: () -> Unit,
    onEnhancedImageReady: (Uri, Bitmap) -> Unit
) {
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()

    var selectedPreset by remember { mutableStateOf(StudioPreset.WHITE_STUDIO) }
    var selectedLighting by remember { mutableStateOf(StudioLighting.STUDIO_SOFTBOX) }
    var customInstructionText by remember { mutableStateOf("") }

    var currentSourceBitmap by remember { mutableStateOf(originalBitmap) }
    var enhancedBitmap by remember { mutableStateOf<Bitmap?>(null) }
    var isProcessing by remember { mutableStateOf(false) }
    var showOriginal by remember { mutableStateOf(false) }
    var statusMessage by remember { mutableStateOf("Ready to transform") }
    var isCloudGenerated by remember { mutableStateOf(false) }

    fun triggerEnhancement(target: Bitmap? = currentSourceBitmap) {
        val bmp = target ?: return
        if (!isProcessing) {
            coroutineScope.launch {
                isProcessing = true
                statusMessage = "AI Studio: Creating Pure White Studio Shot..."
                val result = GeminiAIService.enhanceProductImage(
                    context = context,
                    inputBitmap = bmp,
                    preset = selectedPreset,
                    lighting = selectedLighting,
                    customInstructions = customInstructionText
                )
                result.onSuccess {
                    enhancedBitmap = it.enhancedBitmap
                    isCloudGenerated = it.isCloudAiGenerated
                    statusMessage = it.message
                }
                isProcessing = false
            }
        }
    }

    fun rotateNormalTool(degrees: Float) {
        val matrix = android.graphics.Matrix().apply { postRotate(degrees) }
        enhancedBitmap?.let { bmp ->
            enhancedBitmap = Bitmap.createBitmap(bmp, 0, 0, bmp.width, bmp.height, matrix, true)
        }
        currentSourceBitmap?.let { src ->
            currentSourceBitmap = Bitmap.createBitmap(src, 0, 0, src.width, src.height, matrix, true)
        }
    }

    // Run initial enhancement on open if originalBitmap is available
    LaunchedEffect(originalBitmap) {
        if (originalBitmap != null && enhancedBitmap == null) {
            triggerEnhancement(originalBitmap)
        }
    }

    Dialog(
        onDismissRequest = onDismiss,
        properties = DialogProperties(usePlatformDefaultWidth = false)
    ) {
        Surface(
            modifier = Modifier
                .fillMaxSize()
                .padding(12.dp),
            shape = RoundedCornerShape(24.dp),
            color = DhaagaSurface,
            tonalElevation = 8.dp
        ) {
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .verticalScroll(rememberScrollState())
                    .padding(16.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                // Header
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Box(
                            modifier = Modifier
                                .size(40.dp)
                                .clip(CircleShape)
                                .background(Brush.linearGradient(listOf(DhaagaPrimary, DhaagaPrimaryLight))),
                            contentAlignment = Alignment.Center
                        ) {
                            Icon(Icons.Default.AutoAwesome, contentDescription = null, tint = Color.White)
                        }
                        Spacer(modifier = Modifier.width(12.dp))
                        Column {
                            Text("AI Studio Enhancer", fontSize = 17.sp, fontWeight = FontWeight.Bold, color = DhaagaTextDark)
                            Text("AI Professional Studio Photography", fontSize = 11.sp, color = DhaagaPrimary, fontWeight = FontWeight.Medium)
                        }
                    }
                    IconButton(onClick = onDismiss) {
                        Icon(Icons.Default.Close, contentDescription = "Close", tint = DhaagaTextMedium)
                    }
                }

                // Main Image Preview Area with Before/After
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(260.dp)
                        .clip(RoundedCornerShape(18.dp))
                        .background(Color(0xFFF0EFEB))
                        .border(1.dp, DhaagaDivider.copy(alpha = 0.5f), RoundedCornerShape(18.dp)),
                    contentAlignment = Alignment.Center
                ) {
                    if (isProcessing) {
                        Column(
                            horizontalAlignment = Alignment.CenterHorizontally,
                            verticalArrangement = Arrangement.Center,
                            modifier = Modifier.padding(24.dp)
                        ) {
                            CircularProgressIndicator(color = DhaagaPrimary, modifier = Modifier.size(50.dp), strokeWidth = 4.dp)
                            Spacer(modifier = Modifier.height(16.dp))
                            Text(
                                "Staging Studio Photography...",
                                fontSize = 15.sp,
                                fontWeight = FontWeight.Bold,
                                color = DhaagaPrimary
                            )
                            Spacer(modifier = Modifier.height(6.dp))
                            Text(
                                statusMessage,
                                fontSize = 12.sp,
                                color = DhaagaTextMedium,
                                textAlign = androidx.compose.ui.text.style.TextAlign.Center
                            )
                        }
                    } else {
                        val displayBitmap = if (showOriginal) currentSourceBitmap else (enhancedBitmap ?: currentSourceBitmap)
                        if (displayBitmap != null) {
                            Image(
                                bitmap = displayBitmap.asImageBitmap(),
                                contentDescription = "Studio Product",
                                contentScale = ContentScale.Fit,
                                modifier = Modifier.fillMaxSize()
                            )
                        } else {
                            AsyncImage(
                                model = originalUri,
                                contentDescription = "Original",
                                contentScale = ContentScale.Fit,
                                modifier = Modifier.fillMaxSize()
                            )
                        }

                        // Compare Toggle Button
                        Box(
                            modifier = Modifier
                                .align(Alignment.BottomEnd)
                                .padding(10.dp)
                                .clip(RoundedCornerShape(30.dp))
                                .background(Color.Black.copy(alpha = 0.78f))
                                .clickable { showOriginal = !showOriginal }
                                .padding(horizontal = 12.dp, vertical = 6.dp)
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Icon(
                                    imageVector = if (showOriginal) Icons.Default.VisibilityOff else Icons.Default.Visibility,
                                    contentDescription = null,
                                    tint = Color.White,
                                    modifier = Modifier.size(15.dp)
                                )
                                Spacer(modifier = Modifier.width(6.dp))
                                Text(
                                    if (showOriginal) "Original Camera" else "Studio Enhanced",
                                    fontSize = 11.sp,
                                    color = Color.White,
                                    fontWeight = FontWeight.SemiBold
                                )
                            }
                        }

                        // Top Quality Badge
                        Box(
                            modifier = Modifier
                                .align(Alignment.TopStart)
                                .padding(10.dp)
                                .clip(RoundedCornerShape(8.dp))
                                .background(if (showOriginal) Color.Gray.copy(alpha = 0.85f) else DhaagaPrimary.copy(alpha = 0.92f))
                                .padding(horizontal = 10.dp, vertical = 4.dp)
                        ) {
                            Text(
                                if (showOriginal) "RAW CAMERA" else if (isCloudGenerated) "NANO BANANA PRO • WHITE STUDIO" else "STUDIO LIGHTING • WHITE STUDIO",
                                fontSize = 10.sp,
                                fontWeight = FontWeight.Bold,
                                color = Color.White,
                                letterSpacing = 0.5.sp
                            )
                        }
                    }
                }

                // Professional E-Commerce Studio Standard Checklist Card
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(14.dp),
                    colors = CardDefaults.cardColors(containerColor = Color(0xFFFAF9F6)),
                    border = BorderStroke(1.dp, DhaagaDivider.copy(alpha = 0.5f))
                ) {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(14.dp),
                        verticalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Text(
                            "Professional E-Commerce Studio Standards:",
                            fontSize = 12.sp,
                            fontWeight = FontWeight.Bold,
                            color = DhaagaTextDark
                        )
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.CheckCircle, contentDescription = null, tint = DhaagaSuccess, modifier = Modifier.size(15.dp))
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Pure White Background (#FFFFFF) — 100% background clutter removed", fontSize = 11.sp, color = DhaagaTextMedium)
                        }
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.CheckCircle, contentDescription = null, tint = DhaagaSuccess, modifier = Modifier.size(15.dp))
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Glare & Shine Removed — Diffused matte lighting, zero harsh flash", fontSize = 11.sp, color = DhaagaTextMedium)
                        }
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.CheckCircle, contentDescription = null, tint = DhaagaSuccess, modifier = Modifier.size(15.dp))
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Orientation & Alignment Fixed — Upright, centered with 75% frame fill", fontSize = 11.sp, color = DhaagaTextMedium)
                        }
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.CheckCircle, contentDescription = null, tint = DhaagaSuccess, modifier = Modifier.size(15.dp))
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Clean Shadowless Presentation — Pristine, catalog-ready product isolation", fontSize = 11.sp, color = DhaagaTextMedium)
                        }
                    }
                }

                Spacer(modifier = Modifier.height(2.dp))

                // Action Buttons - Row 1: Rotation Tools (Instant Local Rotate) & AI Re-enhance
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    OutlinedButton(
                        onClick = { rotateNormalTool(-90f) },
                        modifier = Modifier
                            .weight(1f)
                            .height(46.dp),
                        shape = RoundedCornerShape(12.dp),
                        contentPadding = PaddingValues(horizontal = 4.dp)
                    ) {
                        Icon(Icons.AutoMirrored.Filled.RotateLeft, contentDescription = null, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(6.dp))
                        Text("Rotate Left", fontSize = 11.sp, fontWeight = FontWeight.SemiBold, maxLines = 1, softWrap = false, color = DhaagaTextDark)
                    }

                    OutlinedButton(
                        onClick = { rotateNormalTool(90f) },
                        modifier = Modifier
                            .weight(1f)
                            .height(46.dp),
                        shape = RoundedCornerShape(12.dp),
                        contentPadding = PaddingValues(horizontal = 4.dp)
                    ) {
                        Icon(Icons.AutoMirrored.Filled.RotateRight, contentDescription = null, modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(6.dp))
                        Text("Rotate Right", fontSize = 11.sp, fontWeight = FontWeight.SemiBold, maxLines = 1, softWrap = false, color = DhaagaTextDark)
                    }

                    OutlinedButton(
                        onClick = { triggerEnhancement(currentSourceBitmap) },
                        enabled = !isProcessing,
                        modifier = Modifier
                            .weight(1.2f)
                            .height(46.dp),
                        shape = RoundedCornerShape(12.dp),
                        contentPadding = PaddingValues(horizontal = 4.dp)
                    ) {
                        Icon(Icons.Default.Refresh, contentDescription = null, modifier = Modifier.size(15.dp))
                        Spacer(modifier = Modifier.width(4.dp))
                        Text("Re-enhance", fontSize = 11.sp, fontWeight = FontWeight.SemiBold, maxLines = 1, softWrap = false, color = DhaagaTextDark)
                    }
                }

                // Action Buttons - Row 2: Cancel & Use Photo
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                ) {
                    OutlinedButton(
                        onClick = onDismiss,
                        modifier = Modifier
                            .weight(1f)
                            .height(48.dp),
                        shape = RoundedCornerShape(14.dp)
                    ) {
                        Text("Cancel", fontSize = 13.sp, fontWeight = FontWeight.Medium, maxLines = 1, softWrap = false, color = DhaagaTextDark)
                    }

                    Button(
                        onClick = {
                            val finalBitmap = enhancedBitmap ?: currentSourceBitmap
                            if (finalBitmap != null) {
                                try {
                                    val cacheFile = File(context.cacheDir, "studio_enhanced_${System.currentTimeMillis()}.jpg")
                                    FileOutputStream(cacheFile).use { fos ->
                                        finalBitmap.compress(Bitmap.CompressFormat.JPEG, 92, fos)
                                    }
                                    val fileUri = Uri.fromFile(cacheFile)
                                    onEnhancedImageReady(fileUri, finalBitmap)
                                } catch (e: Exception) {
                                    onEnhancedImageReady(originalUri, finalBitmap)
                                }
                            }
                        },
                        enabled = !isProcessing && (enhancedBitmap != null || currentSourceBitmap != null),
                        modifier = Modifier
                            .weight(1.8f)
                            .height(48.dp),
                        shape = RoundedCornerShape(14.dp),
                        colors = ButtonDefaults.buttonColors(containerColor = DhaagaPrimary)
                    ) {
                        Icon(Icons.Default.CheckCircle, contentDescription = null, tint = Color.White, modifier = Modifier.size(18.dp))
                        Spacer(modifier = Modifier.width(6.dp))
                        Text("Use Studio Photo", fontSize = 13.sp, fontWeight = FontWeight.Bold, maxLines = 1, softWrap = false, color = Color.White)
                    }
                }
            }
        }
    }
}
